# Generated by Django 4.2.2 on 2023-07-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="device_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="manufacturer",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="dimension",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="due_date_value",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="DeviceManufacturer",
        ),
    ]
