# Generated by Django 4.2.2 on 2023-07-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_device_device_id_alter_device_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="device_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
